sudo: required
dist: trusty
language: node_js
before_script: npm cache clear
before_install: npm install -g npm@latest
node_js:
  - "5"
  - "4"
  - "3"
  - "2"
  - "1"
  - "iojs"
  - "0.12"
  - "0.10"

